version: '3.8'
services:
  db:
    container_name: educ-db
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "5432:5432"
    restart: always
  app:
    build: .
    container_name: educ-app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${DB_HOST}:${DB_PORT}@${DB_USER}/${DB_NAME}
      NODE_ENV: development
      PORT: 3007
      DOCKER_IP: '127.0.0.1'
    ports:
      - "3007:3007"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/src
      - /app/scripts
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: educ-pgadmin
    logging:
      driver: none
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8888:80"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  src:
  node_modules:
  pgadmin-data:
